### ISSUE TITLE
Only works one direction

### ISSUE THREAD

**Issue by 0xfgarcia** [chmod666org/scaleway-ipmove#1]
Hi,

Only works change ip from server1 to server2, server2 to server1. ¿?

Change README.MD:
add organization argument to command line.

Thanks!

**Comment by 0xfgarcia** [comment]
Ok, solved.

Script get current server id from server that is running the script. Very sophisticated, well done.

**Comment by chmod666org** [comment]
Cool. Closing the issue :)
